#spring.profiles.active: prod
spring:
  application:
    name: crbet-admin
  dataSource:
    url: "jdbc:mysql://localhost:3306/crbet_admin?useTimezone=true&serverTimezone=America/Sao_Paulo"
    username: 'root'
    password: '#Root123'
    driver-class-name: com.mysql.cj.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
#    hibernate.ddl-auto: update
#    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8080
  servlet:
    context-path: /crbets-admin
#security:
#  sessions: NEVER
logging:
  config: classpath:log4j2.xml
 
# app params
betwin:
  security:
    jwtSecret: meuPauDeTanga
    jwtExpiration: 86400
  config:
    commissionPercent: 0.10

---
spring:
  profiles: dev
  dataSource:
    url: "jdbc:mysql://gamasetdb.cjghoaa1m0um.us-east-1.rds.amazonaws.com:3306/crbet_admin_dev?useTimezone=true&serverTimezone=America/Sao_Paulo"
    username: gamasetdb
    password: '#gamasetdb2019'

---
server:
  port: 8180
spring:
  profiles: prod
  dataSource:
    url: "jdbc:mysql://gamasetdb.cjghoaa1m0um.us-east-1.rds.amazonaws.com:3306/crbet_admin_prod?useTimezone=true&serverTimezone=America/Sao_Paulo"
    username: gamasetdb
    password: '#gamasetdb2019'
