spring.profiles.active: dev
spring:
  application:
    name: crbet-admin-api
  dataSource:
    url: "jdbc:mysql://localhost:3306/crbet_admin?useTimezone=true&serverTimezone=America/Sao_Paulo"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8080
  servlet:
    context-path: /crbets-admin
#security:
#  sessions: NEVER
logging:
  config: classpath:log4j2.xml
  

# app params
betwin:
  security:
    jwtSecret: meuPauDeTanga
    jwtExpiration: 86400
  config:
    commissionPercent: 0.10
    
---
spring:
  profiles: dev
  dataSource:
    url: "jdbc:mysql://gamasetdb.cjghoaa1m0um.us-east-1.rds.amazonaws.com:3306/crbet_admin_dev?useTimezone=true&serverTimezone=America/Sao_Paulo"
    username: gamasetdb
    password: '#gamasetdb2019'

---
server:
  port: 8180
spring:
  profiles: prod
  dataSource:
    url: "jdbc:mysql://gamasetdb.cjghoaa1m0um.us-east-1.rds.amazonaws.com:3306/crbet_admin_prod?useTimezone=true&serverTimezone=America/Sao_Paulo"
    username: gamasetdb
    password: '#gamasetdb2019'
